export const REAL_SYMBOLS = [
    // --- US MARKETS (35) ---
    { symbol: 'AAPL', name: 'Apple Inc.' },
    { symbol: 'MSFT', name: 'Microsoft Corp.' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.' },
    { symbol: 'TSLA', name: 'Tesla Inc.' },
    { symbol: 'NVDA', name: 'NVIDIA Corp.' },
    { symbol: 'META', name: 'Meta Platforms' },
    { symbol: 'ADBE', name: 'Adobe Inc.' },
    { symbol: 'NFLX', name: 'Netflix Inc.' },
    { symbol: 'DIS', name: 'Walt Disney Co.' },
    { symbol: 'CRM', name: 'Salesforce Inc.' },
    { symbol: 'AMD', name: 'Advanced Micro Devices' },
    { symbol: 'INTC', name: 'Intel Corp.' },
    { symbol: 'CSCO', name: 'Cisco Systems' },
    { symbol: 'ORCL', name: 'Oracle Corp.' },
    { symbol: 'JPM', name: 'JPMorgan Chase' },
    { symbol: 'V', name: 'Visa Inc.' },
    { symbol: 'MA', name: 'Mastercard Inc.' },
    { symbol: 'WMT', name: 'Walmart Inc.' },
    { symbol: 'COST', name: 'Costco Wholesale' },
    { symbol: 'PG', name: 'Procter & Gamble' },
    { symbol: 'KO', name: 'Coca-Cola Co.' },
    { symbol: 'PEP', name: 'PepsiCo Inc.' },
    { symbol: 'HD', name: 'Home Depot' },
    { symbol: 'NKE', name: 'Nike Inc.' },
    { symbol: 'LLY', name: 'Eli Lilly & Co.' },
    { symbol: 'UNH', name: 'UnitedHealth Group' },
    { symbol: 'PFE', name: 'Pfizer Inc.' },
    { symbol: 'ABBV', name: 'AbbVie Inc.' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific' },
    { symbol: 'CVX', name: 'Chevron Corp.' },
    { symbol: 'XOM', name: 'Exxon Mobil' },
    { symbol: 'UPS', name: 'United Parcel Service' },
    { symbol: 'BA', name: 'Boeing Co.' },
    { symbol: 'GE', name: 'GE Aerospace' },

    // --- INDIAN MARKETS (55) ---
    { symbol: 'RELIANCE', name: 'Reliance Industries' },
    { symbol: 'TCS', name: 'Tata Consultancy Services' },
    { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd' },
    { symbol: 'INFY', name: 'Infosys Ltd' },
    { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd' },
    { symbol: 'SBIN', name: 'State Bank of India' },
    { symbol: 'BHARTIARTL', name: 'Bharti Airtel' },
    { symbol: 'LICI', name: 'LIC of India' },
    { symbol: 'HINDUNILVR', name: 'Hindustan Unilever' },
    { symbol: 'ITC', name: 'ITC Ltd' },
    { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank' },
    { symbol: 'AXISBANK', name: 'Axis Bank Ltd' },
    { symbol: 'LT', name: 'Larsen & Toubro' },
    { symbol: 'BAJFINANCE', name: 'Bajaj Finance' },
    { symbol: 'ASIANPAINT', name: 'Asian Paints' },
    { symbol: 'MARUTI', name: 'Maruti Suzuki India' },
    { symbol: 'TITAN', name: 'Titan Company' },
    { symbol: 'SUNPHARMA', name: 'Sun Pharma' },
    { symbol: 'ADANIENT', name: 'Adani Enterprises' },
    { symbol: 'ULTRACEMCO', name: 'UltraTech Cement' },
    { symbol: 'JSWSTEEL', name: 'JSW Steel' },
    { symbol: 'TATASTEEL', name: 'Tata Steel' },
    { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto' },
    { symbol: 'M&M', name: 'Mahindra & Mahindra' },
    { symbol: 'POWERGRID', name: 'Power Grid Corp' },
    { symbol: 'NTPC', name: 'NTPC Ltd' },
    { symbol: 'ONGC', name: 'ONGC' },
    { symbol: 'ADANIPORTS', name: 'Adani Ports' },
    { symbol: 'COALINDIA', name: 'Coal India' },
    { symbol: 'GRASIM', name: 'Grasim Industries' },
    { symbol: 'HDFCLIFE', name: 'HDFC Life' },
    { symbol: 'SBILIFE', name: 'SBI Life Insurance' },
    { symbol: 'NESTLEIND', name: 'Nestle India Ltd' },
    { symbol: 'DRREDDY', name: 'Dr. Reddys Labs' },
    { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals' },
    { symbol: 'EICHERMOT', name: 'Eicher Motors' },
    { symbol: 'WIPRO', name: 'Wipro Ltd' },
    { symbol: 'TECHM', name: 'Tech Mahindra' },
    { symbol: 'HCLTECH', name: 'HCL Technologies' },
    { symbol: 'BPCL', name: 'Bharat Petroleum' },
    { symbol: 'CIPLA', name: 'Cipla Ltd' },
    { symbol: 'BRITANNIA', name: 'Britannia Industries' },
    { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp' },
    { symbol: 'UPL', name: 'UPL Ltd' },
    { symbol: 'ADANIPOWER', name: 'Adani Power' },
    { symbol: 'TATACONSUM', name: 'Tata Consumer Products' },
    { symbol: 'INDUSINDBK', name: 'IndusInd Bank' },
    { symbol: 'HINDALCO', name: 'Hindalco Industries' },
    { symbol: 'DIVISLAB', name: 'Divis Laboratories' },
    { symbol: 'TATAMOTORS', name: 'Tata Motors' },
    { symbol: 'SHREECEM', name: 'Shree Cement' },
    { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv' },
    { symbol: 'ADANIGREEN', name: 'Adani Green Energy' },
    { symbol: 'ZOMATO', name: 'Zomato Ltd' },
    { symbol: 'NYKAA', name: 'FSN E-Commerce (Nykaa)' },

    // --- GLOBAL MARKETS (10) ---
    { symbol: 'TSM', name: 'TSMC ADR' },
    { symbol: 'ASML', name: 'ASML Holding' },
    { symbol: 'SAP', name: 'SAP SE ADR' },
    { symbol: 'BABA', name: 'Alibaba Group' },
    { symbol: 'TM', name: 'Toyota Motor ADR' },
    { symbol: 'SONY', name: 'Sony Group ADR' },
    { symbol: 'HSBC', name: 'HSBC Holdings ADR' },
    { symbol: 'AZN', name: 'AstraZeneca ADR' },
    { symbol: 'SHEL', name: 'Shell PLC ADR' },
    { symbol: 'BHP', name: 'BHP Group ADR' }
];

export const isValidSymbol = (symbol) => {
    return REAL_SYMBOLS.some(s => s.symbol === symbol.toUpperCase());
};
